services:
  nanook-website:
    image: ghcr.io/humans-not-required/nanook-website:dev
    container_name: nanook-website
    restart: unless-stopped
    ports:
      - "3009:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
